- README.md
- jira/README.md
- jira/dc-apps-performance-toolkit-user-guide.md
- jira/jira.yml
- jira/util/populate_db.sh
- jira/util/upload_attachments.sh
- Support of latest Enterprise Release **Jira 7.13.6**
- Chromedriver version bump to 77.0.3865.40 to support Chrome 77.
- Updated documentation to reflect Jira 7.13.6 support
> Release 1.0.5 beta

- jira/dc-apps-performance-toolkit-user-guide.md
> fix xml_backup.zip link

- app/util/data_preparation/jira/api.py
- app/util/data_preparation/jira/prepare-data.py
https://bulldog.internal.atlassian.com/browse/DCA-207
> DCA-207: Filter out JSD and Jira Business projects/tickets

- app/selenium_ui/confluence/modules.py
Send_keys does not work on a parent element. Need to specify exact element.
> DCA-244 selenium edit page

- app/util/data_preparation/confluence/prepare-data.py
* filter out blogs created by JMeter
* increase the default number of blogs for prepare data step
> improve prepare data for blogs

- README.md
- README.md to reflect correct status of supported Atlassian apps
> Release 1.1.1 beta

- app/util/analytics.py
- app/util/data_preparation/api/confluence_clients.py
- app/util/data_preparation/api/jira_clients.py
Do not merge this PR due to parallel changes need to the dcapt-tooling repo in analytics writer to database script.
> [DO NOT MERGE] Add application version to customer analytics

- app/util/analytics.py
Fixed the seed to not be Michael's silly string
> Fixed seed

- app/util/confluence/populate_db.sh
- app/util/confluence/upload_attachments.sh
- app/util/jira/populate_db.sh
- app/util/jira/upload_attachments.sh
Added machine-friendly progress bar for wget downloads needed for CI runs.
> Dca 290 improve stats

- app/jmeter/bitbucket.jmx
https://bulldog.internal.atlassian.com/browse/DCA-329
> DCA-329: Change generation of repo url and user credentials to read from csv

- README.md
- docs/bitbucket/README.md
- docs/confluence/README.md
- docs/jira/README.md
> DCA-321 Git as requirement and README for bitbucket

- app/jmeter/confluence.jmx
- app/jmeter/jira.jmx
- app/util/data_preparation/confluence/prepare-data.py
- app/util/data_preparation/jira/prepare-data.py
- remove user-agent from Jmeter Jira and Confluence
- suppress InsecureRequestWarning for https case in prepare data for Jira and Confluence
> Remove user agent from jmeter

- app/util/data_preparation/bitbucket/prepare-data.py
https://bulldog.internal.atlassian.com/browse/DCA-330
> DCA-330: Make scripts stop with error if multiple threads can use the same repo

- app/jmeter/bitbucket.jmx
https://bulldog.internal.atlassian.com/browse/DCA-314
> DCA-314: [BB JMeter] Do not remove all ssh keys from admin user when adding new

- app/jmeter/bitbucket.jmx
https://bulldog.internal.atlassian.com/browse/DCA-324
> DCA-324: [BB JMeter] Un-hardcode '/tmp/giterrors.log'

- app/bitbucket.yml
- app/util/analytics.py
- app/util/data_preparation/api/bitbucket_clients.py
- enabled selenium scenario
- added get_bitbucker_version api
- added bbs logic for analytics
> DCA-333 enable bbs selenium scenario and added analytics part for bbs

- app/bitbucket.yml
Changes for bbs as per https://github.com/atlassian/dc-app-performance-toolkit/pull/133
> jmeter and chromedriver versions bump for bbs

- app/util/data_preparation/api/abstract_clients.py
- app/util/data_preparation/api/bitbucket_clients.py
- app/util/data_preparation/api/jira_clients.py
- app/util/data_preparation/bitbucket/prepare-data.py
https://bulldog.internal.atlassian.com/browse/DCA-342
> DCA-342: Handle permission issue on Bitbucket

- app/jmeter/bitbucket.jmx
https://bulldog.internal.atlassian.com/browse/DCA-335
> DCA-335: [BB JMeter] Hide `chmod 400 ssh key` action from results output

- app/jmeter/bitbucket.jmx
https://bulldog.internal.atlassian.com/browse/DCA-332
> DCA-332: [BB JMeter] Make "Add ssh key on Bitbucket" action be not visible

- app/util/data_preparation/api/bitbucket_clients.py
- app/util/data_preparation/bitbucket/prepare-data.py
https://bulldog.internal.atlassian.com/browse/DCA-344
> DCA-344: Inconsistent work of prepare-data script with users

- app/jmeter/bitbucket.jmx
https://bulldog.internal.atlassian.com/browse/DCA-339
> DCA-339: Rename BB JMeter actions according to our convention

- docs/dc-apps-performance-toolkit-user-guide-bitbucket.md
- docs/dc-apps-performance-toolkit-user-guide-jira.md
https://bulldog.internal.atlassian.com/browse/DCA-327
> DCA-327: Complete BB user guide

- docs/jira/README.md
Minor formating changes to jira docs
> NONE: Update README.md

- docs/dc-apps-performance-toolkit-user-guide-bitbucket.md
> NONE: Update user guide for Bitbucket

- app/bitbucket.yml
- app/jmeter/bitbucket.jmx
https://bulldog.internal.atlassian.com/browse/DCA-349
> DCA-349: Prevent excessive load to bb server from too much efficient host machine for dcap

- app/util/conf.py
Merge **after** release 1.3.0 only.
> toolkit version bump to 2.0.0

- docs/dc-apps-performance-toolkit-user-guide-bitbucket.md
Notes: separate PR created in Marketplace repo - https://bitbucket.org/atlassian-developers/marketplace/pull-requests/227/dcapt-fix-bbs-example-typo/diff
> NONE: fix typo in BBS user guide doc

- app/util/analytics.py
- docs/bitbucket/README.md
- docs/confluence/README.md
- docs/dc-apps-performance-toolkit-user-guide-bitbucket.md
- docs/dc-apps-performance-toolkit-user-guide-confluence.md
- docs/dc-apps-performance-toolkit-user-guide-jira.md
- docs/jira/README.md
Generate a new file under the results folder: `results_summary.log`.
File contains a detailed summary of the run with a user-friendly error messages if any.
Example:
> Dca-318 results validation

- app/util/data_preparation/api/jira_clients.py
- app/util/data_preparation/jira/prepare-data.py
https://bulldog.internal.atlassian.com/browse/DCA-415
>  DCA-415: Change get request method on post

- CODEOWNERS
Also after merging this PR, code owners review should be enabled in branch settings.
> Added default code owners for dev branch

- app/util/analytics.py
- app/util/data_preparation/api/bitbucket_clients.py
> fix dataset info analytics.py

- app/util/bitbucket/populate_db.sh
- app/util/bitbucket/upload_attachments.sh
- app/util/confluence/populate_db.sh
- app/util/confluence/upload_attachments.sh
- app/util/jira/populate_db.sh
- app/util/jira/upload_attachments.sh
https://bulldog.internal.atlassian.com/browse/DCA-364
> DCA-364: Improve error handling in case product version was not retrieved in populate_db files

- app/util/bitbucket/populate_db.sh
- app/util/bitbucket/upload_attachments.sh
https://bulldog.internal.atlassian.com/browse/DCA-465?workflowName=Software+Simplified+Workflow+for+Project+DA&stepId=1
> DCA-465: Fix the check that validates if the nodes is NFS

- app/util/data_preparation/bitbucket/prepare-data.py
- app/util/data_preparation/confluence/prepare-data.py
- app/util/data_preparation/jira/prepare-data.py
https://bulldog.internal.atlassian.com/browse/DCA-312
> DCA-312: Add extra logging of limitations into bzt log

- app/selenium_ui/bitbucket/pages/selectors.py
> more precise selection for comment button

- README.md
- docs/dc-apps-performance-toolkit-user-guide-bitbucket.md
- docs/dc-apps-performance-toolkit-user-guide-confluence.md
- docs/dc-apps-performance-toolkit-user-guide-jira.md
Enterprise release was changed to Long Term Support release.
> None: Rename docs LTS release

- docs/dc-apps-performance-toolkit-user-guide-jira.md
https://bulldog.internal.atlassian.com/browse/DCA-352
> DCA-352:Jira full index time consistency

- app/selenium_ui/bitbucket_ui.py
- app/selenium_ui/confluence_ui.py
- app/selenium_ui/conftest.py
- app/selenium_ui/jira_ui.py
- app/util/conf.py
- docs/bitbucket/README.md
- docs/confluence/README.md
- docs/jira/README.md
https://bulldog.internal.atlassian.com/browse/DCA-627
> DCA-627:Read webdriver visible from yml file

- app/util/data_preparation/confluence_prepare_data.py
https://bulldog.internal.atlassian.com/browse/DCA-654
> confluence/DCA-654:Get data by perf_user for the dataset

- app/util/api/bitbucket_clients.py
- app/util/data_preparation/bitbucket_prepare_data.py
https://bulldog.internal.atlassian.com/browse/DCA-662
> bitbucket/DCA-662:Check bitbucket user has admin permissions

- app/util/api/confluence_clients.py
- app/util/data_preparation/confluence_prepare_data.py
https://bulldog.internal.atlassian.com/browse/DCA-661
> DCA-661:Add check if confluence user has admin permissons

- docs/dc-apps-performance-toolkit-user-guide-bitbucket.md
- docs/dc-apps-performance-toolkit-user-guide-confluence.md
- docs/dc-apps-performance-toolkit-user-guide-jira.md
**Also, please check cost estimation, maybe you will find some issues or missed services!!!**
https://hello.atlassian.net/wiki/spaces/DC/pages/809011595/AWS+services+pricing+estimation
> DCA-345:Evaluate Jira and Confluence recommended hardware profile

- app/bitbucket.yml
- app/confluence.yml
- app/jira.yml
- app/selenium_ui/conftest.py
https://bulldog.internal.atlassian.com/browse/DCA-717
> DCA-717:Set eng language to the chrome browser

- docs/dc-apps-performance-toolkit-user-guide-bitbucket.md
https://bulldog.internal.atlassian.com/browse/DCA-696
> DCA-696:Update bitbucket documentation

- README.md
- app/util/confluence/populate_db.sh
- app/util/confluence/upload_attachments.sh
- docs/dc-apps-performance-toolkit-user-guide-confluence.md
https://bulldog.internal.atlassian.com/browse/DCA-766
> DCA-766:Bump new Confluence version 7.4.4

- app/selenium_ui/confluence/pages/pages.py
- app/util/analytics/analytics.py
- app/util/analytics/analytics_utils.py
- app/util/analytics/application_info.py
- app/util/analytics/log_reader.py
- app/util/api/bitbucket_clients.py
https://bulldog.internal.atlassian.com/browse/DCA-434
> DCA-434:Check if run has extensibility

- README.md
- app/util/jira/populate_db.sh
- app/util/jira/upload_attachments.sh
- docs/dc-apps-performance-toolkit-user-guide-jira.md
https://bulldog.internal.atlassian.com/browse/DCA-765
You can check bzt run results and cpu% in ticket
> DCA-765:Bump new Jira version 8.5.8

- app/util/bitbucket/populate_db.sh
- app/util/confluence/populate_db.sh
- app/util/jira/populate_db.sh
Update postgres version in populate_db file
> NONE:Update postgres version

- app/jmeter/jsd.jmx
- app/jsd.yml
https://bulldog.internal.atlassian.com/browse/DCA-817
> DCA-817: [JSD JMeter] create initial script

- README.md
- app/util/confluence/populate_db.sh
- app/util/confluence/upload_attachments.sh
- docs/dc-apps-performance-toolkit-user-guide-confluence.md
https://bulldog.internal.atlassian.com/browse/DCA-839
> DCA-839:Update documentation and scripts for confluence 7.4.5

- app/selenium_ui/jsd/modules_agents.py
- app/selenium_ui/jsd/pages/agent_pages.py
- app/selenium_ui/jsd/pages/agent_selectors.py
- app/selenium_ui/jsd_ui_agents.py
https://bulldog.internal.atlassian.com/browse/DCA-880
> [JSD Selenium] DCA-880:Add view customer request action

- app/selenium_ui/jsd/modules_agents.py
- app/selenium_ui/jsd/pages/agent_pages.py
- app/selenium_ui/jsd/pages/agent_selectors.py
- app/selenium_ui/jsd_ui_agents.py
https://bulldog.internal.atlassian.com/browse/DCA-878
> [JSD Selenium] DCA-878: browse customers page

- app/jmeter/jsd.jmx
https://bulldog.internal.atlassian.com/browse/DCA-872
> DCA-872: [JSD JMeter] Add browse jsd projects action

- app/jmeter/jsd.jmx
https://bulldog.internal.atlassian.com/browse/DCA-871
> [JSM JMeter] DCA-871: View service desk request

- app/jmeter/jsd.jmx
https://bulldog.internal.atlassian.com/browse/DCA-863
> [JSM JMeter] DCA-863: Add request comment

- app/jmeter/jsd.jmx
https://bulldog.internal.atlassian.com/browse/DCA-870
> [JSM JMeter] DCA-870:Add view workload report action

- app/jmeter/jsd.jmx
https://bulldog.internal.atlassian.com/browse/DCA-936
> DCA-936:Add view all open queue medium

- app/jmeter/jsm.jmx
- app/jsm.yml
https://bulldog.internal.atlassian.com/browse/DCA-921
> [JSM JMeter] DCA-921:Update jsd -> jsm

- app/jmeter/jsm_agents.jmx
- app/jsm.yml
> [JSM JMeter] Devide actions by small and medium projects; Merge view queue actions

- app/jmeter/jsm_agents.jmx
- app/jmeter/jsm_customers.jmx
https://bulldog.internal.atlassian.com/browse/DCA-822
> DCA-822:Remove requests for view queue action

- app/jmeter/jira.jmx
https://bulldog.internal.atlassian.com/browse/DCA-964
> DCA-964:Update naming for jira actions

- app/jmeter/confluence.jmx
https://bulldog.internal.atlassian.com/browse/DCA-965
> DCA-965:Update naming for confluence actions

- app/extension/jsm/extension_locust_agents.py
- app/extension/jsm/extension_locust_customers.py
- app/jmeter/jsm_agents.jmx
- app/jmeter/jsm_customers.jmx
- app/locustio/jsm/agents/agents_http_actions.py
- app/locustio/jsm/agents_locustfile.py
- app/locustio/jsm/customers/customers_http_actions.py
- app/locustio/jsm/customers_locustfile.py
https://bulldog.internal.atlassian.com/browse/DCA-976
> DCA-976:Add action name to the jsm_customer_measure and jsm_agent_measure decorators

- README.md
- app/util/confluence/populate_db.sh
- app/util/confluence/upload_attachments.sh
- docs/dc-apps-performance-toolkit-user-guide-confluence.md
https://bulldog.internal.atlassian.com/browse/DCA-990
> DCA-990:Update documentation and scripts with confluence version 7.4.6

- README.md
- app/util/bitbucket/populate_db.sh
- app/util/bitbucket/upload_attachments.sh
- docs/dc-apps-performance-toolkit-user-guide-bitbucket.md
https://bulldog.internal.atlassian.com/browse/DCA-992
> DCA-992:Bump bitbucket version 7.6.2

- app/jmeter/jsm_agents.jmx
https://bulldog.internal.atlassian.com/browse/DCA-1005
> DCA-1005:Fix add_jmeter_comment action

- app/selenium_ui/jsm/pages/agent_pages.py
https://bulldog.internal.atlassian.com/browse/DCA-1008
> DCA-1008:Fix agent selenium add comment action

- app/util/api/jira_clients.py
- app/util/data_preparation/jsm_prepare_data.py
- app/util/project_paths.py
prepare_data execution time: 34 seconds on CI
> DCA-1001: JSM CI - investigate jsm bzt fails

- app/jmeter/bitbucket.jmx
- app/jmeter/confluence.jmx
- app/jmeter/jira.jmx
- app/jmeter/jsm_agents.jmx
- app/jmeter/jsm_customers.jmx
Reverts atlassian/dc-app-performance-toolkit#502
> Revert "Correct misspelling of "Assertion" on jira.jmx"

- app/extension/confluence/extension_locust.py
- app/extension/jira/extension_locust.py
- app/extension/jsm/extension_locust_agents.py
- app/extension/jsm/extension_locust_customers.py
- app/locustio/common_utils.py
- app/locustio/confluence/http_actions.py
- app/locustio/jira/http_actions.py
- app/locustio/jsm/agents/agents_http_actions.py
- app/locustio/jsm/customers/customers_http_actions.py
- docs/dc-apps-performance-toolkit-user-guide-confluence.md
- docs/dc-apps-performance-toolkit-user-guide-jira.md
- docs/dc-apps-performance-toolkit-user-guide-jsm.md
https://bulldog.internal.atlassian.com/browse/DCA-999
> DCA- 999:Run app specific test with admin

- docs/dc-apps-performance-toolkit-user-guide-confluence.md
> DCA-1024:Add catalina options to the user guide

- docs/dc-apps-performance-toolkit-user-guide-bitbucket.md
Reverts atlassian/dc-app-performance-toolkit#529
DC deployments team had fixed the problem: https://bulldog.internal.atlassian.com/browse/DCD-1232
> Revert "increase bb instance type"

- app/jmeter/jira.jmx
https://bulldog.internal.atlassian.com/browse/DCA-960
> [JIRA]:DCA-960:Update jmeter request for new jira versions

- app/jmeter/jira.jmx
Reverts atlassian/dc-app-performance-toolkit#572
> Revert "[JIRA]:DCA-960:Update jmeter request for new jira versions"

- app/jmeter/jira.jmx
https://bulldog.internal.atlassian.com/browse/DCA-1087
> [JIRA]: check variants of retrieving variables in jmeter

- app/reports_generation/csv_chart_generator.py
- app/reports_generation/scripts/chart_generator.py
- app/reports_generation/scripts/summary_aggregator.py
> DCA-1078 add scenario status on chart

- app/jmeter/confluence.jmx
https://bulldog.internal.atlassian.com/browse/DCA-1088
> [Confluence]:DCA-1088:Update approach to retrieving variables

- app/selenium_ui/confluence/pages/pages.py
https://bulldog.internal.atlassian.com/browse/DCA-1104
> [Confluence]:DCA-1104: Fix selenium login if node id doesn't exists

- app/jmeter/jsm_agents.jmx
- app/jmeter/jsm_customers.jmx
https://bulldog.internal.atlassian.com/browse/DCA-1107
> [JSM]:DCA-1107:Update approach of retrieving variables

- app/util/api/abstract_clients.py
- app/util/api/jira_clients.py
- app/util/data_preparation/jira_prepare_data.py
- app/util/data_preparation/jsm_prepare_data.py
https://bulldog.internal.atlassian.com/browse/DCA-1116?atlLinkOrigin=c2xhY2staW50ZWdyYXRpb258aXNzdWU%3D
> [JIRA/JSM] DCA-1116:Add reindex info check

- app/selenium_ui/bitbucket/pages/selectors.py
For details see See https://ecosystem.atlassian.net/browse/DAPT-19
The PR target `dev` branch in favour of #608 targeting `master`
> DCAPT-19 improve css selector for PR merge submit button

- app/util/api/abstract_clients.py
- app/util/api/jira_clients.py
- app/util/data_preparation/jira_prepare_data.py
- app/util/data_preparation/jsm_prepare_data.py
Reverts atlassian/dc-app-performance-toolkit#609
> Revert "[JIRA/JSM] DCA-1116:Add reindex info check"

- app/util/data_preparation/confluence_prepare_data.py
https://bulldog.internal.atlassian.com/browse/DCA-1083
> DCA-1083:Update filter for getting blogs

- app/datasets/crowd/examples/users.csv
- app/util/crowd/populate_db.sh
- app/util/data_preparation/crowd_prepare_data.py
@mmizin Could you please check this version in CI and approve in case of success.
> Added crowd populate db

- README.md
- app/util/bitbucket/populate_db.sh
- app/util/bitbucket/upload_attachments.sh
- docs/dc-apps-performance-toolkit-user-guide-bitbucket.md
https://bulldog.internal.atlassian.com/browse/DCA-1155
> [BITBUCKET] DCA-1155:Update documentation with new BB version 7.6.7

- README.md
- app/util/confluence/populate_db.sh
- app/util/confluence/upload_attachments.sh
- docs/dc-apps-performance-toolkit-user-guide-confluence.md
https://bulldog.internal.atlassian.com/browse/DCA-1157
> [CONFLUENCE] DCA-1157:Update documentation for confluence 7.4.9

- app/selenium_ui/jsm/pages/agent_pages.py
- app/selenium_ui/jsm/pages/agent_selectors.py
https://bulldog.internal.atlassian.com/browse/DCA-1198
> [JSM] DCA-1198: jsm stability improvements

- app/selenium_ui/bitbucket/pages/selectors.py
https://bulldog.internal.atlassian.com/browse/DCA-1234
> DCA-1234:Update commits locator

- docs/dc-apps-performance-toolkit-user-guide-bitbucket.md
https://bulldog.internal.atlassian.com/browse/DCA-1216
> DCA-1216:Update BB user guide

- app/selenium_ui/bamboo/modules.py
- app/selenium_ui/bamboo/pages/pages.py
- app/selenium_ui/bamboo/pages/selectors.py
Reverts atlassian/dc-app-performance-toolkit#784
> Revert "Added check of the selenium logout action"

- app/util/bitbucket/populate_db.sh
permission check by creation and drop of a TEST db, this way the main db used is still up and running without breaking bitbucket by dropping it without having the possibility to re-create it.
> added check for user permissions

- app/util/api/confluence_clients.py
added "retry()" decorator  for "is_remote_api_enabled" check in confluence_clients.py
> conlfuence_clients.py modified

- app/confluence.yml
Set failures>25% within 300s, stop as failed to meet Capacity test requirements
> refactor: set failures>25% within 300s, stop as failed

- app/bamboo.yml
- app/bitbucket.yml
- app/confluence.yml
- app/crowd.yml
- app/jira.yml
- app/jsm.yml
- app/util/jmeter/start_jmeter_ui.py
- docs/dc-apps-performance-toolkit-user-guide-bamboo.md
Jmete 5.6 does not work properly with upload emoji test.
> Downgrade JMeter version to 5.5 due to problem with emoji test

- Dockerfile
Reverts atlassian/dc-app-performance-toolkit#1226
> Revert "Update java in docker file"

- app/util/analytics/analytics.py
- app/util/analytics/analytics_utils.py
Reverts atlassian/dc-app-performance-toolkit#1222
> Revert "Reporting/add specific and node count results"

- app/bamboo.yml
- app/bitbucket.yml
- app/confluence.yml
- app/jira.yml
- app/jsm.yml
Reverts atlassian/dc-app-performance-toolkit#1256
> Revert "CI-created PR with Chromedriver updates 121"

- app/util/bamboo/bamboo_dataset_generator/pom.xml
Reverts atlassian/dc-app-performance-toolkit#1253
> Revert "Update dependency com.jayway.jsonpath:json-path to v2.9.0 [SECURITY]"

- app/util/pre_run/environment_compliance_check.py
Script fails on master astlassian/dcapt container which has old Chrome 120, while locally chomedriver was 122.
> Add no-sandbox argument

- Dockerfile
- README.md
- app/bamboo.yml
- app/bitbucket.yml
- app/confluence.yml
- app/crowd.yml
- app/jira.yml
- app/jsm.yml
- app/util/pre_run/environment_checker.py
- app/util/pre_run/environment_compliance_check.py
* Bump DCAPT docker image base debian image from version 11 to 12
* Switch docker image Java 11 to Java 21
* Add Python 3.12
* Remove python 3.8 from docs
* JMeter 5.5 -> JMeter 5.6
* Remove Java 11 from java check
> DCA-2206 bump java version

- app/extension/confluence/extension_ui.py
- app/locustio/confluence/http_actions.py
- app/selenium_ui/confluence/pages/selectors.py
to avoid the automatic redirection
> CONFSRVDEV-33309: Add the noRedirect query param to the viewpage.action URL in the Python script

- app/locustio/confluence/http_actions.py
… spaceKey and title to avoid automatic redirection
> confsrvdev -33309 Change display URL to the viewpage.action

- app/jmeter/bamboo.jmx
- app/jmeter/confluence.jmx
> DCA-2353 Bamboo 2sv Jmeter and fix app specific user login for conf

- README.md
- app/util/k8s/dcapt-snapshots.json
Reverts atlassian/dc-app-performance-toolkit#1647
> Revert "update crowd version to 6.2.0"
