atlassian/dc-app-performance-toolkit

- jira/jmeter/jira.jmx
Remove redundant jmeter view results tree listener. 
Keeping one as "disabled" to be enabled for debugging purposes.
> NONE: Remove redundant jmeter view results tree listener

- jira/jmeter/jira.jmx
Request 610 /plugins/servlet/gadgets/dashboard-diagnostics was hard-coded to send http in the uri parameter. Fixing this by using ${application.protocol} instead.
> Fix 610 sampler being hard-coded to http

- README.md
- app/util/confluence/index-snapshot.sh
- app/util/confluence/index-sync.sh
- docs/dc-apps-performance-toolkit-user-guide-confluence.md
- docs/dc-apps-performance-toolkit-user-guide-jira.md
A script that waits until index snapshot is generated.
WARNING:
User Guide is not updated yet with how to use this script. Work in progress.
> DCA-238 index snapshot script

- app/jmeter/confluence.jmx
- app/selenium_ui/confluence/modules.py
- app/util/data_preparation/api/confluence_clients.py
- app/util/data_preparation/confluence/prepare-data.py
* fixed JMeter edit page <p> tag issue
* fixed JMeter extend_action wrong syntax
* minor fixes in JMeter script
* add prepare data filtering: JMeter created pages, selenium created pages and space home pages
* refactored WebDriverWait usage to _wait_until
* changed Selenium Edit page to not change page title (not needed as reduces the number of pages "good" for a run)
> jmeter script fixes, refactoring, prepare-data filtering

- requirements.txt
This reverts commit 54e9e34e4f4ff05d3e3303ab5893a3cdf7dadcf6.
> Revert "DCA-278:Bump bzt version to 1.14.0 (#73)"

- requirements.txt
Bump libs versions to support python 3.8
> DCA-302: Bump libraries versions to support python3.8

- app/util/confluence/upload_attachments.sh
- app/util/jira/upload_attachments.sh
Instead of 2 000 000 lines in a log we will have 200 dots.
> Reduce untar log

- app/util/data_preparation/jira/prepare-data.py
Issue found by the vendor.
If project count is more then ~1200 projects (depending on project key length), next request get issues fails with 400 error "Request header is too large".
> limit number of projects for jira

- app/selenium_ui/conftest.py
- docs/confluence/README.md
- docs/jira/README.md
@jkim2-atlassian couple of vendors are complaining about "InvalidSessionIdException" allover Selenium actions. It is very difficult to reproduce this issue locally, but I was able to see a couple of those failures on my local Mac and on local Docker. I was not able to understand why this had happened, but it looks like some chromedriver/Chrome versions combination flaky issue. And the problem is in this get_w3c_timing method. As we are not using these stats anyway, I propose to remove this code to reduce customers' flakiness rate. Any thoughts?
> Remove w3c timings

- app/jira.yml
- app/util/data_preparation/confluence/prepare-data.py
- app/util/data_preparation/jira/prepare-data.py
Edge case found by the vendor: issues search fails if project key is the same as jql reserved word, e.g. `INT`.
Added project keys escaping with double quotes in jql query.
> Jira escape project keys

- app/jmeter/bitbucket.jmx
https://bulldog.internal.atlassian.com/browse/DCA-319?atlLinkOrigin=c2xhY2staW50ZWdyYXRpb258aXNzdWU%3D
> DCA-319: Fix "Add ssh key on Bitbucket" on Windows

- app/jmeter/confluence.jmx
- app/jmeter/jira.jmx
- app/selenium_ui/conftest.py
Each time login is failed, all next actions will be skipped. 
In the picture above - an example of the current implementation for Confluence. Failed login does not affect other actions.
> DCA-350 skip whole tests if login failed

- app/jmeter/jira.jmx
Remove hipchat requests from jira.jmx as jira 8.9+ does not have them.
> Remove hipchat requests from jira.jmx

- Dockerfile
Original image size:
dc-app-performance-toolkit 3.89GB
New image size:
dc-app-performance-toolkit-new 3.83GB
Unfortunately Github doesn't allow to change origin for PR's created from web UI, so I recreated it using regular git. 
Fix of https://github.com/atlassian/dc-app-performance-toolkit/pull/344
> Reduced cache size for Docker

- docs/dc-apps-performance-toolkit-user-guide-jira.md
`dc-apps-performance-toolkit-user-guide-jira.md` still says that the officially supported LTS is  `8.5.6`, but the `README.md` and `populate-db.sh` say `8.5.8`.
> Update versions of jira in jira guide

- app/jmeter/bitbucket.jmx
- app/jmeter/confluence.jmx
- app/jmeter/jira.jmx
- app/jmeter/jsm_agents.jmx
- app/jmeter/jsm_customers.jmx
Many occurences of "Asserion" instead of "Assertion". This caused some tests to fail.
> Correct misspelling of "Assertion" on jira.jmx

- app/confluence.yml
- app/jira.yml
- app/jsm.yml
JMeter runs actions with the same percentages in the same loop. Randomize percentages to make actions distribution better.
> DCA-1084 adjust percentages of actions for jira, confluence and jsm

- app/util/default_test_actions.json
Remove "jmeter_view_page:view_page_tree" after updating Confluence default requsts
> NONE:Clean JMeter default actions

- app/selenium_ui/jsm/pages/agent_pages.py
While running the performance tests for JSM with the large dataset, I find ~6% of the repetitions of the 'selenium_agent_add_comment' test failing with the following exception:
```python
Exception: ('Failed measure: selenium_agent_add_comment - Exception', Exception('Failed measure: selenium_agent_add_comment:add comment - MoveTargetOutOfBoundsException', MoveTargetOutOfBoundsException('move target out of bounds\n  (Session info: headless chrome=90.0.4430.85)', None, None)))
```
A screenshot from one of the failing tests are found below:
It is my assumption that the Selenium agent fails to write in the text editor as some of the GUI elements are not in the current viewport.
The changes in this pull request makes the agent scroll to the GUI elements that it will click on or type in before …
> [JSM] Fix periodic failures of Selenium test 'selenium_agent_add_comment'

- app/locustio/common_utils.py
- requirements.txt
Locust has deprecated `request_success` and `request_failure` hooks.
> DCA-1397 bump taurus version up to 1.16.0

- app/util/confluence/populate_db.sh
permission check by creation and drop of a TEST db, this way the main db used is still up and running without breaking confluence by dropping it without having the possibility to re-create it.
> added check for user permissions

- app/jmeter/confluence.jmx
Confluence 8.1 introduced additional whitespace into the HTML tags; we need to change the regular expression extracting the `pageId` to account for it.
**Version 8.0**
```
<a  id="editPageLink" href="/wiki/pages/editpage.action?pageId=1004923276"
```
**Version 8.1**
```
<a  id="editPageLink"                href="/wiki/pages/editpage.action?pageId=1004923276"
```
> Fix the regex to extract the pageId from the page source

- app/selenium_ui/conftest.py
Right now I am running tests to confirm if my changes will not impact critical browser metrics.
> refactor: add logic to not save confluence.page.view to .jtl

- app/util/k8s/terminate_cluster.py
- requirements.txt
This will make the cleanup script a bit more reliable, especially when it comes to subnet deletion. By default there are 3 tries with a 10 second timeout, except for subnets because sometimes resources in a terminating state still use subnets (or at least AWS API thinks so).
> Use retry lib in cleanup script

- app/util/k8s/dcapt.tfvars
1 product pod and exec env pod require at least 2 instances.
So having min_cluster capacity as 2 will speedup deployment.
> Set min_cluster_capacity to 2

- Dockerfile
- app/bamboo.yml
- app/bitbucket.yml
- app/confluence.yml
- app/crowd.yml
- app/jira.yml
- app/jsm.yml
- app/util/conf.py
- app/util/k8s/README.MD
- docs/dc-apps-performance-toolkit-user-guide-bamboo.md
- docs/dc-apps-performance-toolkit-user-guide-bitbucket.md
- docs/dc-apps-performance-toolkit-user-guide-confluence.md
- docs/dc-apps-performance-toolkit-user-guide-crowd.md
- docs/dc-apps-performance-toolkit-user-guide-jira.md
- docs/dc-apps-performance-toolkit-user-guide-jsm.md
- Bump TerraForm docker image tag to `atlassianlabs/terraform:2.7.9` to fix MIME type deployment issue
- `git pull` from `master` branch
- activate virtual env for the toolkit (see README.md for details)
- `pip install -r requirements.txt`
Use the same `atlassianlabs/terraform` image tag to deploy, upgrade, and undeploy the environment.
> Release 8.2.1

- app/util/jmeter/start_jmeter_ui.py
New flag for `start_jmeter.py script`: `--skip-check` to skip hostname validation in case you want to check app parters kpi.jtl file for errors, but do not have any up running clusters. With this flag no need to comment out the validation code.
> Improve jmeter start with new flag

- app/jmeter/confluence.jmx
When a page is visited via the legacy /display path or viewpage.action without the noRedirect query parameter, it will automatically redirect to a new URL in the form /spaces/<space-key>/pages/<page-id>/<page-title-slug>
In this PR, we add the noRedirect query parameter to the viewpage.action URL or change the /display path to the new format.
> CONFSRVDEV-33309: Modify confluence.jmx to avoid unnecessary URL redirection when visiting a page or blog post

- app/selenium_ui/confluence/pages/pages.py
In upcoming Confluence release 10.0, the login screen wait() logic does not work correctly and selenium tests fail at login. This is a fix for that.
Tested with 8.5.0, 9.2.0, 10.0
> add better wait logic for login form
